name: Deploying to Internet Computer

env:
  DFX_VERSION: 0.15.2
  IDENTITY_PEM: ${{ secrets.DFX_IDENTITY }}
  INIT_COMMAND: npm install && npm run build
  DFX_DEPLOY_COMMAND: dfx deploy --network=ic --no-wallet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Checkout
        uses: actions/checkout@v3

      - name: Set up dfx
        uses: aviate-labs/setup-dfx@v0.2.6
        with:
          dfx-version: ${{ env.DFX_VERSION }}
        env:
          DFX_IDENTITY_PEM: ${{ env.IDENTITY_PEM }}

      - name: Change dfx identity
        run: dfx identity use action

      - name: Init project and deploy to Internet Computer
        run: |
          ${{ env.INIT_COMMAND }}
          ${{ env.DFX_DEPLOY_COMMAND }}